name: dpp-env
channels:
  - conda-forge
dependencies:
  - fastapi=0.115.8
  - ipykernel=6.29.5
  - ipython=8.32.0
  - matplotlib=3.10.0
  - numpy=1.26.4
  - pandas=2.2.3
  - pydantic=2.10.6
  - python=3.11.11
  - python-dotenv=1.0.1
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - tensorflow=2.17.0
  - uvicorn=0.34.0